# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc65272c27199652b936c28264bf770f385243f00d91b69f7424ca298466964855fa146b80c8e747737e4fbce1928e6488b7eb8a5571b777cd9ec27fb1b9d5ee

test:
  secret_key_base: 220fd1845e81695caee029fa3d598129302fbeb01c40d4755d0a14fcb47624c01787f20da78b66e9f25f3858019fcf983ae38b7b7164920e35604d2f85e437e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
